behaviors:
  HeroBrain:
    trainer_type: ppo

    hyperparameters:
      # Hyperparameters common to PPO and SAC
      batch_size: 64
      buffer_size: 1024
      learning_rate: 3.0e-4
      learning_rate_schedule: linear

      # PPO-specific hyperparameters
      beta: 5.0e-3
      beta_schedule: constant
      epsilon: 0.2
      epsilon_schedule: linear
      lambd: 0.95
      num_epoch: 3
      shared_critic: False

    # Configuration of the neural network (common to PPO/SAC)
    network_settings:
      vis_encode_type: match3
      normalize: true
      hidden_units: 128
      num_layers: 2
      # memory
      memory:
        sequence_length: 64
        memory_size: 256

    # Trainer configurations common to all trainers
    max_steps: 1e5
    time_horizon: 64
    summary_freq: 5000
    keep_checkpoints: 5
    checkpoint_interval: 50000
    threaded: true
    init_path: null

    reward_signals:
      # environment reward (default)
      extrinsic:
        strength: 1.0
        gamma: 0.99
        network_settings:
          vis_encode_type: match3
          normalize: true
          hidden_units: 128
          num_layers: 2
          # memory
          memory:
            sequence_length: 64
            memory_size: 256


      # curiosity module
      curiosity:
        strength: 0.02
        gamma: 0.99
        encoding_size: 256
        learning_rate: 3.0e-4
        network_settings:
          vis_encode_type: match3
          normalize: true
          hidden_units: 128
          num_layers: 2


  BossBrain:
    trainer_type: ppo

    hyperparameters:
      # Hyperparameters common to PPO and SAC
      batch_size: 64
      buffer_size: 1024
      learning_rate: 3.0e-4
      learning_rate_schedule: linear

      # PPO-specific hyperparameters
      beta: 5.0e-3
      beta_schedule: constant
      epsilon: 0.2
      epsilon_schedule: linear
      lambd: 0.95
      num_epoch: 3
      shared_critic: False

    # Configuration of the neural network (common to PPO/SAC)
    network_settings:
      vis_encode_type: match3
      normalize: true
      hidden_units: 128
      num_layers: 2
      # memory
      memory:
        sequence_length: 16
        memory_size: 64

    # Trainer configurations common to all trainers
    max_steps: 1e5
    time_horizon: 64
    summary_freq: 5000
    keep_checkpoints: 5
    checkpoint_interval: 50000
    threaded: true
    init_path: null

    reward_signals:
      # environment reward (default)
      extrinsic:
        strength: 1.0
        gamma: 0.99
        network_settings:
          vis_encode_type: match3
          normalize: true
          hidden_units: 128
          num_layers: 2
          # memory
          memory:
            sequence_length: 16
            memory_size: 64

      # curiosity module
      curiosity:
        strength: 0.02
        gamma: 0.99
        encoding_size: 256
        learning_rate: 3.0e-4
        network_settings:
          vis_encode_type: match3
          normalize: true
          hidden_units: 128
          num_layers: 2
